import React, { Fragment } from "react";

import PropTypes from "prop-types";

import "./testimonial17.css";

const Testimonial17 = (props) => {
  return (
    <div className="thq-section-padding">
      <div className="testimonial17-max-width thq-section-max-width">
        <div className="testimonial17-container10">
          <h2>
            {props.heading1 ?? (
              <Fragment>
                <h2 className="testimonial17-text33 thq-heading-2">
                  Testimonials
                </h2>
              </Fragment>
            )}
          </h2>
          <span>
            {props.content1 ?? (
              <Fragment>
                <span className="testimonial17-text31 thq-body-small">
                  I have been using this AI-powered plant disease detection app
                  for a while now, and it has been a game-changer for me. The
                  detailed analysis provided has helped me save several of my
                  plants from potential diseases.
                </span>
              </Fragment>
            )}
          </span>
        </div>
        <div className="thq-grid-2">
          <div className="thq-animated-card-bg-2">
            <div className="thq-animated-card-bg-1">
              <div
                data-animated="true"
                className="thq-card testimonial17-card1"
              >
                <div className="testimonial17-container12">
                  <img
                    alt={props.author1Alt}
                    src={props.author1Src}
                    className="testimonial17-image1"
                  />
                  <div className="testimonial17-container13">
                    <strong>
                      {props.author1Name ?? (
                        <Fragment>
                          <strong className="testimonial17-text32 thq-body-large">
                            John Doe
                          </strong>
                        </Fragment>
                      )}
                    </strong>
                    <span>
                      {props.author1Position ?? (
                        <Fragment>
                          <span className="testimonial17-text34 thq-body-small">
                            Plant Enthusiast
                          </span>
                        </Fragment>
                      )}
                    </span>
                  </div>
                </div>
                <span>
                  {props.review1 ?? (
                    <Fragment>
                      <span className="testimonial17-text25 thq-body-small">
                        Highly recommend this app to all plant lovers out there!
                      </span>
                    </Fragment>
                  )}
                </span>
              </div>
            </div>
          </div>
          <div className="thq-animated-card-bg-2">
            <div className="thq-animated-card-bg-1">
              <div
                data-animated="true"
                className="thq-card testimonial17-card2"
              >
                <div className="testimonial17-container14">
                  <img
                    alt={props.author2Alt}
                    src={props.author2Src}
                    className="testimonial17-image2"
                  />
                  <div className="testimonial17-container15">
                    <strong>
                      {props.author2Name ?? (
                        <Fragment>
                          <strong className="testimonial17-text28 thq-body-large">
                            Jane Smith
                          </strong>
                        </Fragment>
                      )}
                    </strong>
                    <span>
                      {props.author2Position ?? (
                        <Fragment>
                          <span className="testimonial17-text37 thq-body-small">
                            Botanist
                          </span>
                        </Fragment>
                      )}
                    </span>
                  </div>
                </div>
                <span>
                  {props.review2 ?? (
                    <Fragment>
                      <span className="testimonial17-text30 thq-body-small">
                        As a professional botanist, I am impressed by the
                        accuracy of the disease detection results generated by
                        this app. It has become an essential tool in my daily
                        work.
                      </span>
                    </Fragment>
                  )}
                </span>
              </div>
            </div>
          </div>
          <div className="thq-animated-card-bg-2">
            <div className="thq-animated-card-bg-1">
              <div
                data-animated="true"
                className="thq-card testimonial17-card3"
              >
                <div className="testimonial17-container16">
                  <img
                    alt={props.author3Alt}
                    src={props.author3Src}
                    className="testimonial17-image3"
                  />
                  <div className="testimonial17-container17">
                    <strong>
                      {props.author3Name ?? (
                        <Fragment>
                          <strong className="testimonial17-text27 thq-body-large">
                            David Green
                          </strong>
                        </Fragment>
                      )}
                    </strong>
                    <span>
                      {props.author3Position ?? (
                        <Fragment>
                          <span className="testimonial17-text29 thq-body-small">
                            Gardening Enthusiast
                          </span>
                        </Fragment>
                      )}
                    </span>
                  </div>
                </div>
                <span>
                  {props.review3 ?? (
                    <Fragment>
                      <span className="testimonial17-text35 thq-body-small">
                        I love how easy it is to use this app. The chatbot
                        feature is particularly helpful for getting quick
                        answers to my plant health queries.
                      </span>
                    </Fragment>
                  )}
                </span>
              </div>
            </div>
          </div>
          <div className="thq-animated-card-bg-2">
            <div className="thq-animated-card-bg-1">
              <div
                data-animated="true"
                className="thq-card testimonial17-card4"
              >
                <div className="testimonial17-container18">
                  <img
                    alt={props.author4Alt}
                    src={props.author4Src}
                    className="testimonial17-image4"
                  />
                  <div className="testimonial17-container19">
                    <strong>
                      {props.author4Name ?? (
                        <Fragment>
                          <strong className="testimonial17-text24 thq-body-large">
                            Sarah Lee
                          </strong>
                        </Fragment>
                      )}
                    </strong>
                    <span>
                      {props.author4Position ?? (
                        <Fragment>
                          <span className="testimonial17-text26 thq-body-small">
                            Horticulturist
                          </span>
                        </Fragment>
                      )}
                    </span>
                  </div>
                </div>
                <span>
                  {props.review4 ?? (
                    <Fragment>
                      <span className="testimonial17-text36 thq-body-small">
                        This app has revolutionized the way I approach plant
                        care. The supplement suggestions provided have
                        significantly improved the health of my plants.
                      </span>
                    </Fragment>
                  )}
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

Testimonial17.defaultProps = {
  author4Alt: "Image of Sarah Lee",
  author4Name: undefined,
  review1: undefined,
  author4Position: undefined,
  author3Name: undefined,
  author2Name: undefined,
  author1Src:
    "https://images.unsplash.com/photo-1579783902188-1dbf2b672dc8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTcyNTI5ODI0MXw&ixlib=rb-4.0.3&q=80&w=1080",
  author3Src:
    "https://images.unsplash.com/photo-1505682614136-0a12f9f7beea?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTcyNTI5ODI0Mnw&ixlib=rb-4.0.3&q=80&w=1080",
  author3Position: undefined,
  review2: undefined,
  content1: undefined,
  author1Name: undefined,
  heading1: undefined,
  author2Src:
    "https://images.unsplash.com/photo-1484972759836-b93f9ef2b293?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTcyNTI5ODI0Mnw&ixlib=rb-4.0.3&q=80&w=1080",
  author3Alt: "Image of David Green",
  author1Position: undefined,
  author2Alt: "Image of Jane Smith",
  author1Alt: "Image of John Doe",
  review3: undefined,
  review4: undefined,
  author4Src:
    "https://images.unsplash.com/photo-1668643215329-66f88d703734?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTcyNTI5ODI0Mnw&ixlib=rb-4.0.3&q=80&w=1080",
  author2Position: undefined,
};

Testimonial17.propTypes = {
  author4Alt: PropTypes.string,
  author4Name: PropTypes.element,
  review1: PropTypes.element,
  author4Position: PropTypes.element,
  author3Name: PropTypes.element,
  author2Name: PropTypes.element,
  author1Src: PropTypes.string,
  author3Src: PropTypes.string,
  author3Position: PropTypes.element,
  review2: PropTypes.element,
  content1: PropTypes.element,
  author1Name: PropTypes.element,
  heading1: PropTypes.element,
  author2Src: PropTypes.string,
  author3Alt: PropTypes.string,
  author1Position: PropTypes.element,
  author2Alt: PropTypes.string,
  author1Alt: PropTypes.string,
  review3: PropTypes.element,
  review4: PropTypes.element,
  author4Src: PropTypes.string,
  author2Position: PropTypes.element,
};

export default Testimonial17;
